services:
  kafka-b:
    image: docker.io/apache/kafka:4.0.1
    container_name: kafka-b
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-b:9092,EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-b:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

  mongo:
    container_name: mongo
    image: docker.io/mongo:8.0.15
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: messaging
      MONGO_INITDB_ROOT_PASSWORD: messaging
      MONGO_INITDB_DATABASE: messaging

  mongo-express:
      container_name: mongo-express
      image: mongo-express:latest
      ports:
        - "8081:8081"
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: messaging
        ME_CONFIG_MONGODB_ADMINPASSWORD: messaging
        ME_CONFIG_MONGODB_URL: mongodb://messaging:messaging@mongo:27017/messaging?authSource=admin
        ME_CONFIG_BASICAUTH_USERNAME: messaging
        ME_CONFIG_BASICAUTH_PASSWORD: messaging
      depends_on:
        - mongo

  postgres:
    image: docker.io/postgres:18-alpine
    container_name: dev-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: group_messaging_service
    ports:
      - "5432:5432"
